---
title: "R Notebook"
output: html_notebook
---

``` {bash}
sudo apt-get update -y 
sudo apt-get install -y libbz2-dev
sudo apt-get install -y liblzma-dev
```

```{r package install}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("dada2")
```
```{r}
library(dada2)
```


```{r}
BiocManager::install("phangorn")
BiocManager::install("DECIPHER")
install.packages("gridExtra")
```
```{r}
install.packages(.cran_packages)
BiocManager::install(.bioc_packages)
```

```{r}
library("knitr")
library("BiocManager")
.cran_packages <- c("ggplot2", "gridExtra")
.bioc_packages <- c("dada2", "phyloseq", "DECIPHER", "phangorn")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   BiocManager::install(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
```

```{r package install}
install.packages('BiocManager')
library('BiocManager')
BiocManager::install('phyloseq')
```

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("phyloseq", INSTALL_opts = '--no-lock')
```

```{bash}
sudo apt-get install -y libglpk-dev
```

```{r}
BiocManager::install("phyloseq")
```
```{r}
library(phyloseq)
```

```{r}
BiocManager::install("ggrepel")
```
```{r}
BiocManager::install("caret")
```

```{r}
BiocManager::install("ggnetwork")
```
